Login state and check, landing page
bcgov/court-of-appeal pull request #32
Opened 2021-07-22 21:33 UTC by danbigthink

2021-07-22 22:20 UTC, seeker25 requested changes

2021-07-22 22:20 UTC, seeker25 commented on api/app/config/environment.js
> +const DEVELOPMENT_ENV = 'development';
You're probably going to want to get docker and manage.sh to work with this 

https://github.com/bcgov/court-of-appeal/blob/b631797066ae05fd395c85f83527b79533a1a5e1/docker/manage#L227

So it's straight forward for us to put the environment variables in Openshift.

2021-07-22 22:37 UTC, seeker25 commented
So far so good a few concerns:

![image](https://user-images.githubusercontent.com/3484109/126717857-ae05429f-33ba-40b6-b825-f36f156f9032.png)

From the picture: 

1.	Extra spacing needs to be fixed
2.	A few requests being sent? Too many?
3.	Spacing at the bottom? 



4.	I don’t see the logout button anymore?
5.	Also I think there is a way to pass a ?next= parameter when logging in? That way it can take us directly back to the dashboard instead of going back to the main page, having to call AJAX is_logged_in and then redirecting?

2021-07-22 23:15 UTC, seeker25 commented
I've fixed a few.. I see the logout doesn't show up  because i'm missing the secrets

2021-07-22 23:29 UTC, seeker25 commented
It looks like landing.css is bleeding over other styles.

2021-07-22 23:36 UTC, danbigthink commented
> I've fixed a few.. I see the logout doesn't show up because i'm missing the secrets

- I have no idea what the BCEID_LOGIN_URL env value should be. Can you update that or send me the url?

- I can take out the in memory service, should we leave it there if NODE_ENV === 'test'?

- The changes look good, thanks. You had mentioned you didn't want the logout link showing in the header (once logged in) so I hid it unless NODE_ENV===development. 

- I had tried the redirect to /dashboard the way you have it and that didn't work, using start-dev with craco.config.js causes all typed in url's into the address bar to return a 404 if you try to use external nav (ie. http://localhost:3000/court-of-appeal can be typed into the address bar but http://localhost:3000/court-of-appeal/dashboard cannot). 

- I'll get this all running in docker.

2021-07-22 23:37 UTC, seeker25 commented
I've fixed the second to last point.. just doing one small tweak for the landing page spacing right now

2021-07-22 23:43 UTC, seeker25 commented
I don't think we use the BCEID_LOGIN URL?

2021-07-22 23:50 UTC, seeker25 commented
"You had mentioned you didn't want the logout link showing in the header (once logged in) so I hid it unless NODE_ENV===development."

Sorry it shouldn't show up if on the landing page, should probably still show up for users though because they'll need to log out.

I think most of the outstanding issues have been fixed, just get it working under docker (with environment variables).. and we'll merge it.

2021-07-22 23:53 UTC, danbigthink commented
@seeker25 
- Changing that now - Sorry it shouldn't show up if on the landing page, should probably still show up for users though because they'll need to log out.

2021-07-22 23:54 UTC, seeker25 commented
Excellent, looks pretty good man!

2021-07-22 23:55 UTC, danbigthink commented
> Excellent, looks pretty good man!

Thanks, I'll finish up the docker and build stuff tomorrow afternoon.

2021-07-29 03:30 UTC, seeker25 commented on openshift/templates/api/api-deploy.test.param
> +SM_LOGOUT_URL_PREFIX=https://logontest.gov.bc.ca/clp-cgi/logoff.cgi
Probably need this done for DEV / PROD as well?

2021-07-29 03:31 UTC, seeker25 commented
Url for PROD is https://logon.gov.bc.ca/clp-cgi/logoff.cgi

2021-07-29 16:40 UTC, seeker25 commented on openshift/templates/api/api-deploy.overrides.sh
> +  readParameter "SM_LOGOUT_URL_PREFIX - Please provide the Siteminder logout url prefix for the environemnt.  The default is a blank string." SM_LOGOUT_URL_PREFIX "" "false"
Don't need this here if I remember correctly

2021-07-29 16:40 UTC, seeker25 commented on openshift/templates/api/api-deploy.overrides.sh
> +  writeParameter "SM_LOGOUT_URL_PREFIX" "prompt_skipped" "false"
Don't need this here if I remember correctly

2021-07-29 21:25 UTC, merged